apiVersion: v1
kind: Pod
metadata:
  name: test-pod-worker2
spec:
  nodeName: my-second-cluster-worker2
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Hello from nginx on worker2" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'