apiVersion: v1
kind: Namespace
metadata:
  name: cilium-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: cilium-demo
  labels:
    app: client
spec:
  nodeSelector:
    kubernetes.io/hostname: cilium-lab-worker
  containers:
    - name: client
      image: nicolaka/netshoot:v0.16
      command: ["sh", "-c", "sleep infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: cilium-demo
  labels:
    app: server
spec:
  nodeSelector:
    kubernetes.io/hostname: cilium-lab-worker2
  containers:
    - name: server
      image: busybox:1.37.0
      command:
        - sh
        - -c
        - |
          mkdir -p /www
          echo "Hello from the server pod" > /www/index.html
          httpd -f -p 8080 -h /www
